vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        thumbnail:
            uri_prefix: /images/thumbnails
            upload_destination: '%kernel.project_dir%/public/images/thumbnails'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
